name: dart_grpc_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0
  async: ^2.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
